import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../application/providers.dart';
import '../../domain/entities/production.dart';

/// Form for creating/editing a production batch.
class ProductionForm extends ConsumerStatefulWidget {
  const ProductionForm({super.key});

  @override
  ConsumerState<ProductionForm> createState() => ProductionFormState();
}

class ProductionFormState extends ConsumerState<ProductionForm> {
  final _formKey = GlobalKey<FormState>();
  final _quantityController = TextEditingController();
  final _notesController = TextEditingController();

  @override
  void dispose() {
    _quantityController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> submit() async {
    if (!_formKey.currentState!.validate()) return;

    try {
      final config = await ref.read(productionControllerProvider).getPeriodConfig();
      final now = DateTime.now();
      final production = Production(
        id: '', // Will be generated by repository
        date: now,
        quantity: int.parse(_quantityController.text),
        period: config.getPeriodForDate(now),
        notes: _notesController.text.isEmpty ? null : _notesController.text,
      );

      await ref.read(productionControllerProvider).createProduction(production);

      if (!mounted) return;
      Navigator.of(context).pop();
      ref.invalidate(productionStateProvider);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Production enregistrée')),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Erreur: ${e.toString()}')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          TextFormField(
            controller: _quantityController,
            decoration: const InputDecoration(
              labelText: 'Quantité (packs)',
              prefixIcon: Icon(Icons.water_drop),
              helperText: 'Nombre de packs produits',
            ),
            keyboardType: TextInputType.number,
            validator: (v) {
              if (v == null || v.isEmpty) return 'Requis';
              final qty = int.tryParse(v);
              if (qty == null || qty <= 0) return 'Quantité invalide';
              return null;
            },
          ),
          const SizedBox(height: 16),
          TextFormField(
            controller: _notesController,
            decoration: const InputDecoration(
              labelText: 'Notes (optionnel)',
              prefixIcon: Icon(Icons.note),
            ),
            maxLines: 3,
          ),
        ],
      ),
    );
  }
}
