// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw89xmCa70mpG6T3BU0Qhn7xLqidt5fuY',
    appId: '1:343526894268:web:43f288028cd20eb3e33eb9',
    messagingSenderId: '343526894268',
    projectId: 'elyf-group-app',
    authDomain: 'elyf-group-app.firebaseapp.com',
    storageBucket: 'elyf-group-app.firebasestorage.app',
    measurementId: 'G-12N52N50ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9cRbvG7QRJtmZQjrawNLMq6XQVQq9o20',
    appId: '1:343526894268:android:3e7b21f657acd7c9e33eb9',
    messagingSenderId: '343526894268',
    projectId: 'elyf-group-app',
    storageBucket: 'elyf-group-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxlwesBcdl0wKlAEZN7JJJoUJHRKKS9RY',
    appId: '1:343526894268:ios:60a8407b0dba8118e33eb9',
    messagingSenderId: '343526894268',
    projectId: 'elyf-group-app',
    storageBucket: 'elyf-group-app.firebasestorage.app',
    iosBundleId: 'com.example.elyfGroupeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxlwesBcdl0wKlAEZN7JJJoUJHRKKS9RY',
    appId: '1:343526894268:ios:60a8407b0dba8118e33eb9',
    messagingSenderId: '343526894268',
    projectId: 'elyf-group-app',
    storageBucket: 'elyf-group-app.firebasestorage.app',
    iosBundleId: 'com.example.elyfGroupeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw89xmCa70mpG6T3BU0Qhn7xLqidt5fuY',
    appId: '1:343526894268:web:82ded927de51887ae33eb9',
    messagingSenderId: '343526894268',
    projectId: 'elyf-group-app',
    authDomain: 'elyf-group-app.firebaseapp.com',
    storageBucket: 'elyf-group-app.firebasestorage.app',
    measurementId: 'G-P7J33GNG1S',
  );
}
